launch script is goog

diff --git a/CV-injector b/CV-injector
--- a/CV-injector
+++ b/CV-injector
@@ -1,2 +1,34 @@
-#!/bin/sh
-./node_modules/.bin/phantomjs scraper.js $1 | node injector.js $2
+#!/bin/bash
+declare -r scriptname=${0##*/}
+declare -r scriptdirectory=${0%/*}
+
+if ! node -v >/dev/null 2>&1; then
+  echo "$scriptname: you must install node.js first, try \`brew install node'" >&2
+  exit 1
+fi
+
+declare -r phantomjs=$scriptdirectory/node_modules/.bin/phantomjs
+
+if [[ ! -f $phantomjs ]]; then
+  echo "$scriptname: you must install phantomjs first, try \`npm install'" >&2
+  exit 1
+fi
+
+while getopts ":h" opt; do
+  case $opt in
+    h)
+      echo "usage: $scriptname <config> <LinkedIn profile URL>"
+      exit 2;;
+    \?)
+      echo "$scriptname: illegal option -- $OPTARG" >&2
+      exit 1;;
+  esac
+done
+shift $(($OPTIND - 1))
+
+if [[ $# -lt 2 ]]; then
+  echo "$scriptname: missing arguments, try \`$scriptname -h'" >&2
+  exit 1
+fi
+
+$phantomjs $scriptdirectory/scraper.js $2 | node $scriptdirectory/injector.js $1
